
<?php if (count($messages) > 0): ?>
<div class="alert">
    <?php foreach ($messages as $message): ?>
        <p><?php echo $message; ?></p>
    <?php endforeach; ?>
</div>
<?php endif; ?>

<a href="<?php echo $this->url('todo/add'); ?>" class="btn btn-success">Hinzufügen</a>

<table class="table">

<?php
/** @var $todos \Todo\Entity\Todo[] */
foreach ($todos as $todo) {
?>
    <tr>
        <td><?php echo $this->escapeHtml($todo->getTodo()); ?></td>
        <td>
            <a href="<?php echo $this->url('todo/edit', array('id' => $todo->getId())); ?>" class="btn btn-info">Edit</a>
            <a href="<?php echo $this->url('todo/delete', array('id' => $todo->getId())); ?>" class="btn btn-warning">Delete</a>
        </td>
    </tr>
<?php
}
?>
</table>
